name: flutter_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  flutter_slidable: ^1.2.0
  shared_preferences: ^2.0.12
  json_serializable: ^6.1.3
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Source Serif Pro
      fonts:
        - asset: fonts/SourceSerifPro-Regular.ttf

  assets:
    - assets/images/

